// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwaihhjyrvinsgciktic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3YWloaGp5cnZpbnNnY2lrdGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzAwMjYsImV4cCI6MjA2MTY0NjAyNn0.8bt77Y6BKTR8wAnUQG7NzXnc1rDuJlwE2vaTlsyBk7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);